# Generated by Django 4.0.4 on 2023-05-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/'),
        ),
    ]
